version: "3"

services:
  app_common:
    container_name: app_pizza
    restart: unless-stopped
    networks:
      - pizza-network

  nginx_common:
    image: nginx
    container_name: nginx_pizza
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - pizza-network

  pgdb_common:
    container_name: postgres_pizza
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_DB_PASS}
      POSTGRES_PASSWORD: ${PG_DB_USER}
      POSTGRES_DB: ${PG_DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${PG_DB_PORT}:5432"
    networks:
      - pizza-network

  swagger_common:
    container_name: swagger_pizza
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: '/docs/openapi.yaml'
    restart: unless-stopped

    networks:
      - pizza-network